package com.saudi.salarycalculator.feature.calculator

import com.saudi.salarycalculator.core.calculator.DefaultNetSalaryCalculatorService
import com.saudi.salarycalculator.core.model.CalculationRecord
import com.saudi.salarycalculator.core.model.CalculationType
import com.saudi.salarycalculator.core.model.EmployeeType
import com.saudi.salarycalculator.core.model.EmploymentSector
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Builds an "unofficial payroll summary" CSV (opens fine in Excel/Sheets/Numbers) from the app's
 * saved NET_SALARY history — a convenience export for someone who has calculated several
 * employees' salaries in this app and wants a single compiled sheet, rather than re-typing every
 * figure by hand.
 *
 * This is deliberately NOT a WPS/SIF file. The official Saudi Wage Protection System format is a
 * strict government spec submitted through Mudad or the employer's bank, and this app has no way
 * to verify its output against that live spec — generating something that *looks* like an
 * official compliance file but might not match it exactly would be a real liability if someone
 * submitted it as-is. So this only ever produces a plain, clearly-labeled reference sheet; actual
 * WPS submission still goes through Mudad / the bank's own portal.
 */
object PayrollSummaryExporter {
  private val netSalaryCalculatorService = DefaultNetSalaryCalculatorService()
  private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.US)

  private val columns = listOf(
    "Calculated On", "Employee Name", "Job Title", "Nationality", "Employment Sector",
    "Contract Type", "Basic Salary", "Housing Allowance", "Transport Allowance",
    "Other Allowances", "Bonus & Commission", "Overtime Pay", "Gross Salary",
    "Employee GOSI", "Employer GOSI", "Total Deductions", "Net Salary (Monthly)",
    "Net Salary (Yearly)", "Estimated EOSB"
  )

  fun write(file: File, records: List<CalculationRecord>) {
    val rows = records
      .filter { it.type == CalculationType.NET_SALARY && it.netSalaryInput != null }
      .sortedByDescending { it.createdAtMillis }

    file.bufferedWriter().use { writer ->
      writer.appendLine(
        "Unofficial payroll summary - NOT an official WPS/SIF file. Submit payroll through " +
          "Mudad or your bank's official WPS portal. Generated by Saudi Salary Calculator: EOSB on " +
          dateFormat.format(Date()) + "."
      )
      writer.appendLine()
      writer.appendLine(columns.joinToString(",") { it.csvEscaped() })

      rows.forEach { record ->
        val input = record.netSalaryInput ?: return@forEach
        val result = netSalaryCalculatorService.calculate(input)
        val row = listOf(
          dateFormat.format(Date(record.createdAtMillis)),
          input.employeeName,
          input.jobTitle,
          if (input.employeeType == EmployeeType.SAUDI) "Saudi" else "Non-Saudi",
          if (input.employmentSector == EmploymentSector.PRIVATE) "Private" else "Government",
          input.contractType.name,
          input.basicSalary.money(),
          input.housingAllowance.money(),
          input.transportAllowance.money(),
          (input.foodAllowance + input.mobileAllowance + input.otherAllowances).money(),
          (input.bonus + input.commission).money(),
          result.overtimePay.money(),
          result.grossSalary.money(),
          result.employeeGosiAmount.money(),
          result.employerGosiAmount.money(),
          result.totalDeductions.money(),
          result.netSalary.money(),
          result.yearlyNetSalary.money(),
          result.estimatedEosb.money()
        )
        writer.appendLine(row.joinToString(",") { it.csvEscaped() })
      }
    }
  }

  /** True if there's at least one saved calculation this export could actually include — lets
   * the UI disable the export action instead of sharing a file with only the disclaimer/header
   * rows and no data. */
  fun hasExportableRecords(records: List<CalculationRecord>): Boolean =
    records.any { it.type == CalculationType.NET_SALARY && it.netSalaryInput != null }

  private fun Double.money(): String = String.format(Locale.US, "%.2f", this)

  private fun String.csvEscaped(): String =
    if (contains(",") || contains("\"") || contains("\n")) {
      "\"${replace("\"", "\"\"")}\""
    } else {
      this
    }
}
